<?php

########################################################################
# Extension Manager/Repository config file for ext: "cundd_time_overview"
#
# Auto generated by Extension Builder 2012-11-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Time Overview',
	'description' => 'Get an overview of your work time',
	'category' => 'plugin',
	'author' => 'Daniel Corn',
	'author_email' => 'info@cundd.net',
	'author_company' => 'cundd',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>